image: node:14

cache:
  paths:
    - node_modules/

stages:
  - build
  - deploy

build-app-proxy-image:
  image: docker:18.09.9
  services:
    - docker:dind
  variables:
    DOCKER_HOST: tcp://docker:2376
    DOCKER_TLS_CERTDIR: "/certs"
  stage: build
  only:
    - develop
  script:
    - docker login registry.gitlab.com --username $CI_MINE_USERNAME --password $CI_MINE_PASSWORD
    - docker build -f ./tools/docker/Dockerfile -t registry.gitlab.com/georgi.apostolov/app-proxy:latest .
    - docker tag registry.gitlab.com/georgi.apostolov/app-proxy:latest registry.gitlab.com/georgi.apostolov/app-proxy:$CI_COMMIT_SHA
    - docker push registry.gitlab.com/georgi.apostolov/app-proxy:$CI_COMMIT_SHA
    - docker push registry.gitlab.com/georgi.apostolov/app-proxy:latest


build:
  stage: build
  when: manual
  only:
    - develop
  script:
    - npm install
